var txtArr0= new Array();
txtArr0.push("0");
txtArr0.push("ezz oh this");
txtArr0.push("2");
txtArr0.push("dzz subceller coal hole");
txtArr0.push("2");
txtArr0.push("twn please be advised");
txtArr0.push("3");
txtArr0.push("ezz eyes will not subside");
txtArr0.push("4");
txtArr0.push("dzz as sediments do");
txtArr0.push("6");
txtArr0.push("twn and their problematic flooding");
txtArr0.push("4");
txtArr0.push("ezz presents");
txtArr0.push("3");
txtArr0.push("dzz the occasional");
txtArr0.push("2");
txtArr0.push("twn [] inconvenience");
txtArr0.push("2");
txtArr0.push("ezz [] insentience");
txtArr0.push("2");
txtArr0.push("dzz [] incontinence");
txtArr0.push("2");
txtArr0.push("twn [] inconsistency's");
txtArr0.push("3");
txtArr0.push("ezz [] incandescent");
txtArr0.push("3");
txtArr0.push("dzz well it’s so bright");
txtArr0.push("4");
txtArr0.push("twn if it were turned off. more");
txtArr0.push("2");
txtArr0.push("ezz it’d be able to see the stars. more");
txtArr0.push("2");
txtArr0.push("dzz and if it didn’t ever turn it off");
txtArr0.push("2");
txtArr0.push("twn well, could just look at them on the ‘net");
txtArr0.push("2");
txtArr0.push("ezz [] inconvenience");
txtArr0.push("2");
txtArr0.push("dzz [] insentience");
txtArr0.push("2");
txtArr0.push("twn [] incontinence");
txtArr0.push("2");
txtArr0.push("ezz [] inconsistency's");
txtArr0.push("2");
txtArr0.push("dzz [] incandescent");
txtArr0.push("2");
txtArr0.push("twn control ");
txtArr0.push("2");
txtArr0.push("ezz print out your thoughts and then");
txtArr0.push("3");
txtArr0.push("dzz print out your thoughts and then");
txtArr0.push("4");
txtArr0.push("twn feedback through the twain scanner");
txtArr0.push("4");
txtArr0.push("ezz feedback through the twain scanner");
txtArr0.push("4");
txtArr0.push("twn and you’ll notice what you’ve forgotten");
txtArr0.push("4");
txtArr0.push("dzz FEAR OF BASEMENTS");
txtArr0.push("3");
txtArr0.push("twn and you’ll notice what you’ve forgotten");
txtArr0.push("3");
txtArr0.push("dzz FEAR OF BASEMENTS");
txtArr0.push("3");
txtArr0.push("twn FEAR OF BASEMENTS");
txtArr0.push("3");
txtArr0.push("ezz a guy's job is: crush the parasite");
txtArr0.push("3");
txtArr0.push("dzz a guy's job is: crush the parasite");
txtArr0.push("3");
txtArr0.push("twn a guy's job is: crush the parasite");
txtArr0.push("3");
txtArr0.push("ezz ammobox");
txtArr0.push("3");
txtArr0.push("dzz ammobox");
txtArr0.push("3");
txtArr0.push("twn ammobox");
txtArr0.push("2");
txtArr0.push("ezz a guy's job is: crush the parasite");
txtArr0.push("2");
txtArr0.push("dzz a guy's job is: crush the parasite");
txtArr0.push("2");
txtArr0.push("twn a guy's job is: crush the parasite");
txtArr0.push("2");
txtArr0.push("ezz ammobox");
txtArr0.push("2");
txtArr0.push("dzz ammobox");
txtArr0.push("2");
txtArr0.push("twn ammobox");
txtArr0.push("2");
txtArr0.push("ezz a guy's job is: crush the parasite");
txtArr0.push("2");
txtArr0.push("dzz a guy's job is: crush the parasite");
txtArr0.push("2");
txtArr0.push("twn a guy's job is: crush the parasite");
txtArr0.push("2");
txtArr0.push("ezz ammobox");
txtArr0.push("2");
txtArr0.push("dzz ammobox");
txtArr0.push("2");
txtArr0.push("twn ammobox");
txtArr0.push("2");
txtArr0.push("ezz FEAR OF BASEMENTS");
txtArr0.push("2");
txtArr0.push("dzz FEAR OF BASEMENTS");
txtArr0.push("2");
txtArr0.push("twn FEAR OF BASEMENTS");
txtArr0.push("2");
txtArr0.push("ezz a guy's job is: crush the parasite");
txtArr0.push("2");
txtArr0.push("dzz a guy's job is: crush the parasite");
txtArr0.push("2");
txtArr0.push("twn a guy's job is: crush the parasite");
txtArr0.push("2");
txtArr0.push("ezz ammobox");
txtArr0.push("2");
txtArr0.push("dzz ammobox");
txtArr0.push("2");
txtArr0.push("twn ammobox");
txtArr0.push("2");
txtArr0.push("ezz a guy's job is: crush the parasite");
txtArr0.push("2");
txtArr0.push("dzz a guy's job is: crush the parasite");
txtArr0.push("2");
txtArr0.push("twn a guy's job is: crush the parasite");
txtArr0.push("2");
txtArr0.push("ezz ammobox");
txtArr0.push("2");
txtArr0.push("dzz ammobox");
txtArr0.push("2");
txtArr0.push("twn ammobox");
txtArr0.push("666");
txtArr0.push("---");

var txtArr1= new Array();

txtArr1.push("0");
txtArr1.push("{ \"true_blue\" : {");
txtArr1.push("");
txtArr1.push("\"the bus is coming\" : \"get out");
txtArr1.push("");
txtArr1.push("in front of your new happenstance,");
txtArr1.push("");
txtArr1.push("go ahead and slip into your");
txtArr1.push("");
txtArr1.push("trousers of the future.\",");
txtArr1.push("");
txtArr1.push("trousers of the future.\",");
txtArr1.push("");
txtArr1.push("trousers of the future.\",");
txtArr1.push("");
txtArr1.push("\"everyone is\" : \"dying to know");
txtArr1.push("");
txtArr1.push("what you will wear to your own\",");
txtArr1.push("");
txtArr1.push("\"will only be\" : \"a quarter-hour");
txtArr1.push("");
txtArr1.push("untill the next sucka rolls by\",");
txtArr1.push("");
txtArr1.push("	\"weird arp\" : \"sounds this guy was");
txtArr1.push("");
txtArr1.push("playing under red, par-can light\",");
txtArr1.push("");
txtArr1.push("	\"difference\" : \"between those");
txtArr1.push("");
txtArr1.push("bathed in the red light and those");
txtArr1.push("");
txtArr1.push("eyes in the darkness.\",");
txtArr1.push("");
txtArr1.push("	\"what what what\" : \"happens to");
txtArr1.push("");
txtArr1.push("those eyes that watch the static");
txtArr1.push("");
txtArr1.push("on the television screen all night");
txtArr1.push("");
txtArr1.push("on the television screen all night\"");
txtArr1.push("");
txtArr1.push("on the television screen all night}, {");
txtArr1.push("");
txtArr1.push("\"do not worry\" : \"about bringing");
txtArr1.push("");
txtArr1.push("more meat\",");
txtArr1.push("");
txtArr1.push("	\"our roaster\" : \"is full,");
txtArr1.push("");
txtArr1.push("anyway\",");
txtArr1.push("");
txtArr1.push("	\"what would the neighbors");
txtArr1.push("");
txtArr1.push("think\" : \"bringing over new");
txtArr1.push("");
txtArr1.push("meat\",");
txtArr1.push("");
txtArr1.push("	\"and joseph\" : \"doesnot know");
txtArr1.push("");
txtArr1.push("where his horn is.\"");
txtArr1.push("");
txtArr1.push("where his horn is.}, {");
txtArr1.push("");
txtArr1.push("\"lost keys during vacation\" :");
txtArr1.push("");
txtArr1.push("\"could have broke into any house,");
txtArr1.push("");
txtArr1.push("really\",");
txtArr1.push("");
txtArr1.push("	\"but thought\" : \"the smell would");
txtArr1.push("");
txtArr1.push("be more atrocious than not\",");
txtArr1.push("");
txtArr1.push("	\"and you could have asked me\" :");
txtArr1.push("");
txtArr1.push("\"which one is yours?\",");
txtArr1.push("");
txtArr1.push("	\"and i could have explained\" :");
txtArr1.push("");
txtArr1.push("\"my own olfactory cues.\"");
txtArr1.push("");
txtArr1.push("ammo box");
txtArr1.push("");
txtArr1.push("ammo box");
txtArr1.push("");
txtArr1.push("ammo box");
txtArr1.push("");
txtArr1.push("ammo box");
txtArr1.push("");
txtArr1.push("throw away all the ammo");
txtArr1.push("");
txtArr1.push("gonna need room for all of the gin");
txtArr1.push("");
txtArr1.push("and granola bars");
txtArr1.push("");
txtArr1.push("that i ate earlier today.");
txtArr1.push("");
txtArr1.push("don’t even care if the ammo box");
txtArr1.push("");
txtArr1.push("don’t have one of those retrofit toilet seats.");
txtArr1.push("");
txtArr1.push("fuck it,");
txtArr1.push("");
txtArr1.push("i don’t mind the rail lines");
txtArr1.push("");
txtArr1.push("---");

var txtArr2= new Array();
txtArr1.push("");
txtArr2.push("{");
txtArr1.push("");
txtArr2.push("{");
txtArr1.push("");
txtArr2.push("{");
txtArr1.push("");
txtArr2.push("\"put two things");
txtArr1.push("");
txtArr2.push("\"put two things");
txtArr1.push("");
txtArr2.push("inside an empty room.\" :");
txtArr1.push("");
txtArr2.push("inside an empty room.\" :");
txtArr1.push("");
txtArr2.push("\"a glass jar");
txtArr1.push("");
txtArr2.push("the kind with the diamond sides\" : \"");
txtArr1.push("");
txtArr2.push("the kind with the diamond sides\" : \"");
txtArr1.push("");
txtArr2.push("filled with almonds.\",");
txtArr1.push("");
txtArr2.push("\"an adult-large uniform\":");
txtArr1.push("");
txtArr2.push("\"an adult-medium uniform\":");
txtArr1.push("");
txtArr2.push("\"an adult-medium uniform\":");
txtArr1.push("");
txtArr2.push("\"one metal chair");
txtArr1.push("");
txtArr2.push("anchored to the ground.\"");
txtArr1.push("");
txtArr2.push("},");
txtArr1.push("");
txtArr2.push("},");
txtArr1.push("");
txtArr2.push("},");
txtArr1.push("");
txtArr2.push("\"two men come into your peripheral vision");
txtArr1.push("");
txtArr2.push("\": \"pick up everything that can be lifted");
txtArr1.push("");
txtArr2.push("and put it atop");
txtArr1.push("");
txtArr2.push("where you sleep\",");
txtArr1.push("");
txtArr2.push("\"walk outside, towards that droning hum\":");
txtArr1.push("");
txtArr2.push("\"record this sound");
txtArr1.push("");
txtArr2.push("bring it back.\",");
txtArr1.push("");
txtArr2.push("and replay it inside the emptied room");
txtArr1.push("");
txtArr2.push("replay it");
txtArr1.push("");
txtArr2.push("\"put two things inside");
txtArr1.push("");
txtArr2.push("an empty room.\":");
txtArr1.push("");
txtArr2.push("{specter");
txtArr1.push("");
txtArr2.push("\"specter\": \"");
txtArr1.push("");
txtArr2.push("the door from your refrigerator.");
txtArr1.push("");
txtArr2.push("specter\",");
txtArr1.push("");
txtArr2.push("the door from your refrigerator.");
txtArr1.push("");
txtArr2.push("\"reparation");
txtArr1.push("");
txtArr2.push("reparation");
txtArr1.push("");
txtArr2.push("the contents of your mailbox.");
txtArr1.push("");
txtArr2.push("reparation");
txtArr1.push("");
txtArr2.push("reparation},");
txtArr1.push("");
txtArr2.push("the contents of your mailbox.");
txtArr1.push("");
txtArr2.push("record the sound of the empty room");
txtArr1.push("");
txtArr2.push("continuously replay it inside the room");
txtArr1.push("");
txtArr2.push("at one increment louder volume.\",");
txtArr1.push("");
txtArr2.push("at one increment louder volume.\",");
txtArr1.push("");
txtArr2.push("record the sound of the filled diamond");
txtArr1.push("");
txtArr2.push("sided jar\": \"replay it inside the room at");
txtArr1.push("");
txtArr2.push("one increment louder volume.\",");
txtArr1.push("");
txtArr2.push("one increment louder volume.\",");
txtArr1.push("");
txtArr2.push("one increment louder volume.\",");
txtArr1.push("");
txtArr2.push("ceramic heat lightbulb\":");
txtArr1.push("");
txtArr2.push("reparation");
txtArr1.push("");
txtArr2.push("\"he also does this");
txtArr1.push("");
txtArr2.push("rope wall climb upside down head dunk");
txtArr1.push("");
txtArr2.push("into white goop");
txtArr1.push("");
txtArr2.push("\"i could try and hold the kernels in my mouth");
txtArr1.push("");
txtArr2.push("\": \"donot swallow them 'till they pop'd!");
txtArr1.push("");
txtArr2.push("donot swallow them 'till they pop'd!");
txtArr1.push("");
txtArr2.push("donot swallow them 'till they pop'd!}");
txtArr1.push("");
txtArr2.push("i could try and hold the kernels in my mouth}");
txtArr1.push("");
txtArr2.push("PUT TWO");
txtArr1.push("");
txtArr2.push("PUT TWO");
txtArr1.push("");
txtArr2.push("PUT TWO");
txtArr1.push("");
txtArr2.push("PUT TWO");
txtArr1.push("");
txtArr2.push("PUT TWO");
txtArr1.push("");
txtArr2.push("---");